# Generated by Django 6.0.3 on 2026-03-12 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myApp", "0002_update_order"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="buyer_name",
        ),
        migrations.RemoveField(
            model_name="order",
            name="buyer_phone",
        ),
        migrations.RemoveField(
            model_name="order",
            name="discount_amount",
        ),
        migrations.RemoveField(
            model_name="order",
            name="paid_at",
        ),
        migrations.RemoveField(
            model_name="order",
            name="payment_method",
        ),
        migrations.RemoveField(
            model_name="order",
            name="payment_ref_id",
        ),
        migrations.RemoveField(
            model_name="order",
            name="payment_status",
        ),
        migrations.RemoveField(
            model_name="order",
            name="shipping_amount",
        ),
        migrations.RemoveField(
            model_name="order",
            name="total_amount",
        ),
        migrations.RemoveField(
            model_name="order",
            name="transaction_id",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[("buyer", "Buyer"), ("seller", "Seller")],
                default="buyer",
                max_length=10,
            ),
        ),
    ]
