# Generated by Django 6.0.3 on 2026-03-14 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myApp", "0005_userprofile_email"),
        ("myApp", "0006_sellerearning_payout"),
    ]

    operations = []
